# Generated by Django 4.1.2 on 2022-11-18 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cp_name', models.CharField(max_length=100)),
                ('cp_phone', models.CharField(max_length=100)),
                ('cp_email', models.CharField(max_length=100)),
                ('cp_msg', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='pro_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='adress',
            field=models.CharField(max_length=50),
        ),
    ]
